const fs = require("fs");
const path = require("path");
const DATA_DIR = path.join(__dirname, "../../../data");
const STORE_FILE = path.join(DATA_DIR, "self-growth-state.json");
const DEFAULT_STATE = { version: "8.5.0", mode: "supervised", growthScore: 86, monthlySavingsPotential: 480, revenuePotential: 2300, performanceGainPotential: 32, conversionGainPotential: 18, lastAnalysisAt: null, actions: [], experiments: [ { id: "exp_onboarding", title: "Onboarding guiado para novos usuários", status: "ready", impact: "Aumentar ativação inicial", risk: "low" }, { id: "exp_deploy_cta", title: "Botão Deploy 1 Clique mais visível", status: "ready", impact: "Aumentar uso do Deploy Center", risk: "low" }, { id: "exp_mobile_waitlist", title: "Lista de espera Megan Mobile", status: "planned", impact: "Validar demanda mobile", risk: "low" } ], opportunities: [ { id: "cost_render", area: "Custos", title: "Revisar plano Render e jobs ociosos", priority: "high", estimatedValue: "R$ 180/mês", action: "auditar serviços e sugerir ajuste de plano" }, { id: "db_indexes", area: "Performance", title: "Criar índices nas tabelas críticas", priority: "high", estimatedValue: "+22% API", action: "gerar plano SQL supervisionado" }, { id: "paid_agents", area: "Receita", title: "Transformar agentes em módulos pagos", priority: "high", estimatedValue: "R$ 1.200/mês", action: "criar página de planos e bundles" }, { id: "support_funnel", area: "Conversão", title: "Melhorar explicação do Deploy Autopilot", priority: "medium", estimatedValue: "+8% conversão", action: "adicionar tutorial operacional no painel" }, { id: "mobile_app", area: "Produto", title: "Preparar Megan Mobile Developer Mode", priority: "medium", estimatedValue: "Novo canal", action: "criar roadmap Android/React Native" } ] };
function ensureStore(){ fs.mkdirSync(DATA_DIR,{recursive:true}); if(!fs.existsSync(STORE_FILE)) fs.writeFileSync(STORE_FILE, JSON.stringify(DEFAULT_STATE,null,2)); }
function readState(){ ensureStore(); try { return {...DEFAULT_STATE, ...JSON.parse(fs.readFileSync(STORE_FILE,"utf8"))}; } catch(_e){ return {...DEFAULT_STATE}; } }
function writeState(state){ ensureStore(); fs.writeFileSync(STORE_FILE, JSON.stringify(state,null,2)); return state; }
function buildDashboard(){ const state=readState(); const highPriority=state.opportunities.filter(i=>i.priority==="high").length; return { ok:true, version:state.version, mode:state.mode, growthScore:state.growthScore, lastAnalysisAt:state.lastAnalysisAt, summary:{ monthlySavingsPotential:state.monthlySavingsPotential, revenuePotential:state.revenuePotential, performanceGainPotential:state.performanceGainPotential, conversionGainPotential:state.conversionGainPotential, opportunities:state.opportunities.length, highPriority, experiments:state.experiments.length, completedActions:state.actions.filter(i=>i.status==="done").length }, opportunities:state.opportunities, experiments:state.experiments, actions:state.actions.slice(0,12) }; }
function runAnalysis(){ const state=readState(); const now=new Date().toISOString(); const action={ id:`analysis_${Date.now()}`, type:"analysis", title:"Análise de crescimento executada", result:"Custos, performance, conversão, produto e receita foram reavaliados.", status:"done", createdAt:now }; writeState({...state,lastAnalysisAt:now,growthScore:Math.min(96,Math.max(state.growthScore,88)),actions:[action,...state.actions].slice(0,50)}); return buildDashboard(); }
function createGrowthPlan(){ const dashboard=buildDashboard(); const steps=dashboard.opportunities.map((item,index)=>({ id:`step_${index+1}`, title:item.title, area:item.area, priority:item.priority, expectedValue:item.estimatedValue, action:item.action, approvalRequired:item.priority==="high" })); return { ok:true, version:"8.5.0", planName:"Self Growth AI - Plano supervisionado", steps }; }
function executeSafeActions(options={}){ const state=readState(); const confirmed=Boolean(options.confirm); const now=new Date().toISOString(); const safe=state.opportunities.filter(i=>i.priority!=="high"||confirmed); const blocked=state.opportunities.filter(i=>i.priority==="high"&&!confirmed); const executed=safe.map(item=>({ id:`growth_${item.id}_${Date.now()}`, type:"growth_action", title:`Preparado: ${item.title}`, result:`Ação supervisionada preparada: ${item.action}.`, status:"done", createdAt:now })); writeState({...state, actions:[...executed,...state.actions].slice(0,50), growthScore:Math.min(99,state.growthScore+(confirmed?4:2))}); return { ok:true, needsConfirmation:blocked.length>0, message:blocked.length?`${executed.length} ação(ões) segura(s) preparada(s). ${blocked.length} ação(ões) de alto impacto aguardam confirmação.`:`${executed.length} ação(ões) de crescimento preparada(s).`, executed, blocked, dashboard:buildDashboard(), plan:createGrowthPlan() }; }
function setMode(mode="supervised"){ const allowed=["manual","supervised","autonomous"]; const nextMode=allowed.includes(mode)?mode:"supervised"; const state=readState(); writeState({...state, mode:nextMode}); return buildDashboard(); }
module.exports = { buildDashboard, runAnalysis, createGrowthPlan, executeSafeActions, setMode };
