const os = require('os');
const fs = require('fs');
const path = require('path');
const childProcess = require('child_process');
const PROJECT_ROOT = path.resolve(__dirname, '../../../..');
const BACKEND_ROOT = path.resolve(PROJECT_ROOT, 'backend');
const FRONTEND_ROOT = path.resolve(PROJECT_ROOT, 'frontend');
const DATA_DIR = path.resolve(BACKEND_ROOT, 'data');
const TASK_FILE = path.resolve(DATA_DIR, 'sovereign-mind-22-tasks.json');
const MEMORY_FILE = path.resolve(DATA_DIR, 'sovereign-mind-22-memory.json');
const DECISION_FILE = path.resolve(DATA_DIR, 'sovereign-mind-22-decisions.json');
const HISTORY_FILE = path.resolve(DATA_DIR, 'sovereign-mind-22-history.json');
function ensureDataFiles() {
  fs.mkdirSync(DATA_DIR, { recursive: true });
  if (!fs.existsSync(TASK_FILE)) fs.writeFileSync(TASK_FILE, '[]');
  if (!fs.existsSync(DECISION_FILE)) fs.writeFileSync(DECISION_FILE, '[]');
  if (!fs.existsSync(HISTORY_FILE)) fs.writeFileSync(HISTORY_FILE, '[]');
  if (!fs.existsSync(MEMORY_FILE)) fs.writeFileSync(MEMORY_FILE, JSON.stringify({ activeObjective: 'Transformar a Megan OS em plataforma operacional controlada por chat.', operatingMode: 'autonomia supervisionada', priorities: ['estabilidade','controle por chat','deploy seguro','visual premium','memoria estrategica'], guardrails: ['confirmar comandos criticos','validar antes de entregar','preservar arquivos existentes'], updatedAt: new Date().toISOString() }, null, 2));
}
function readJson(file, fallback) { try { ensureDataFiles(); return JSON.parse(fs.readFileSync(file, 'utf8')); } catch (_error) { return fallback; } }
function writeJson(file, value) { ensureDataFiles(); fs.writeFileSync(file, JSON.stringify(value, null, 2)); }
function pushHistory(entry) { const history = readJson(HISTORY_FILE, []); history.unshift({ id: `hist_${Date.now()}`, at: new Date().toISOString(), ...entry }); writeJson(HISTORY_FILE, history.slice(0, 120)); }
function pushDecision(entry) { const decisions = readJson(DECISION_FILE, []); const decision = { id: `decision_${Date.now()}`, at: new Date().toISOString(), ...entry }; decisions.unshift(decision); writeJson(DECISION_FILE, decisions.slice(0, 120)); return decision; }
function runCommand(command, cwd = PROJECT_ROOT) { try { const output = childProcess.execSync(command, { cwd, encoding: 'utf8', timeout: 20000, maxBuffer: 1024 * 1024 }); return { ok: true, command, cwd, output: output.trim() || 'Comando executado sem saída.' }; } catch (error) { return { ok: false, command, cwd, output: String(error.stdout || '').trim(), error: String(error.stderr || error.message || 'Erro ao executar comando.').trim() }; } }
function fileInfo(relative) { const absolute = path.join(PROJECT_ROOT, relative); return { file: relative, exists: fs.existsSync(absolute), size: fs.existsSync(absolute) ? fs.statSync(absolute).size : 0 }; }
function readPackage(relative) { const file = path.join(PROJECT_ROOT, relative); if (!fs.existsSync(file)) return null; try { const pkg = JSON.parse(fs.readFileSync(file, 'utf8')); return { file: relative, name: pkg.name, version: pkg.version, scripts: pkg.scripts || {} }; } catch (error) { return { file: relative, error: error.message }; } }
function projectSummary() { return { projectRoot: PROJECT_ROOT, backendRoot: BACKEND_ROOT, frontendRoot: FRONTEND_ROOT, exists: { project: fs.existsSync(PROJECT_ROOT), backend: fs.existsSync(BACKEND_ROOT), frontend: fs.existsSync(FRONTEND_ROOT) }, packages: [readPackage('backend/package.json'), readPackage('frontend/package.json')].filter(Boolean), importantFiles: ['backend/src/app.js','backend/src/server.js','backend/package.json','frontend/src/App.jsx','frontend/src/lib/api.js','frontend/package.json','.env.example'].map(fileInfo) }; }
function getStrategicMemory() { return readJson(MEMORY_FILE, {}); }
function listTasks() { return readJson(TASK_FILE, []); }
function listDecisions() { return readJson(DECISION_FILE, []); }
function healthScore() { const summary = projectSummary(); const existing = summary.importantFiles.filter((item) => item.exists).length; const base = Math.round((existing / summary.importantFiles.length) * 70); const memoryFreeRatio = os.freemem() / Math.max(1, os.totalmem()); return Math.min(100, base + Math.round(memoryFreeRatio * 30)); }
function getSovereignStatus() { const total = os.totalmem(); const free = os.freemem(); const tasks = listTasks(); return { ok: true, module: 'Megan OS 22.0 Operator Sovereign Mind', version: '22.0.0-rebuild', mode: getStrategicMemory().operatingMode || 'autonomia supervisionada', now: new Date().toISOString(), uptimeSeconds: Math.round(process.uptime()), platform: process.platform, node: process.version, cpuCores: os.cpus()?.length || 0, healthScore: healthScore(), memoryUsage: { totalMB: Math.round(total / 1024 / 1024), usedMB: Math.round((total - free) / 1024 / 1024), freeMB: Math.round(free / 1024 / 1024) }, strategicMemory: getStrategicMemory(), pendingTasks: tasks.filter((task) => task.status !== 'done').length, project: projectSummary() }; }
function createTask({ text, priority = 'normal', area = 'operacional', source = 'chat' }) { const tasks = listTasks(); const task = { id: `task_${Date.now()}`, text: String(text), priority, area, status: 'pending', source, createdAt: new Date().toISOString() }; tasks.unshift(task); writeJson(TASK_FILE, tasks.slice(0, 200)); pushHistory({ type: 'task_created', task }); return task; }
function auditSystem() { const backendSyntax = runCommand('node --check src/app.js && node --check src/server.js', BACKEND_ROOT); const checks = [{ name: 'backend_syntax', ok: backendSyntax.ok, detail: backendSyntax.ok ? 'Backend passou na checagem.' : backendSyntax.error || backendSyntax.output }, ...projectSummary().importantFiles.map((item) => ({ name: item.file, ok: item.exists, detail: item.exists ? `${item.size} bytes` : 'arquivo ausente' }))]; const ok = checks.every((check) => check.ok); return { ok, title: 'Auditoria soberana 22.0', checks, recommendation: ok ? 'Sistema principal validado. Próximo passo: npm install e npm run build no frontend.' : 'Há itens pendentes antes do deploy.', status: getSovereignStatus() }; }
function classifyIntent(message) { const text = String(message || '').toLowerCase(); if (/(status|saúde|saude|online|como estamos)/.test(text)) return 'status'; if (/(auditar|validar|verificar erro|analisar sistema|quebrado)/.test(text)) return 'audit'; if (/(tarefas pendentes|listar tarefas|minhas tarefas)/.test(text)) return 'tasks'; if (/(decisões|decisoes|histórico|historico)/.test(text)) return 'decisions'; if (/(prioridade|próximo passo|proximo passo|o que fazer hoje)/.test(text)) return 'priority'; if (/(memória|memoria|objetivo atual)/.test(text)) return 'memory'; if (/^(criar tarefa|delegar tarefa)/.test(text) || /delegar/.test(text)) return 'create_task'; if (/(npm install backend|instalar backend)/.test(text)) return 'install_backend'; if (/(npm install frontend|instalar frontend)/.test(text)) return 'install_frontend'; if (/(build frontend|npm run build|gerar build)/.test(text)) return 'build_frontend'; if (/(git status|status git)/.test(text)) return 'git_status'; return 'general'; }
function buildPriorityAnswer() { const audit = auditSystem(); const failing = audit.checks.filter((check) => !check.ok); return { executiveAnswer: failing.length ? 'Prioridade máxima: corrigir pendências técnicas antes de evoluir.' : 'Prioridade máxima: validar build frontend e preparar deploy controlado.', nextActions: [failing[0] ? `Corrigir: ${failing[0].name}` : 'Rodar npm install no backend e frontend', 'Executar build do frontend', 'Testar login e chat operacional', 'Subir Git somente depois dos testes locais'], pendingTasks: listTasks().filter((task) => task.status !== 'done').slice(0, 8), auditOk: audit.ok }; }
function proposalFor(intent) { if (intent === 'install_backend') return { action: 'install_backend', command: 'npm install', cwd: BACKEND_ROOT, risk: 'baixo', reason: 'Instala dependências do backend.' }; if (intent === 'install_frontend') return { action: 'install_frontend', command: 'npm install', cwd: FRONTEND_ROOT, risk: 'baixo', reason: 'Instala dependências do frontend.' }; if (intent === 'build_frontend') return { action: 'build_frontend', command: 'npm run build', cwd: FRONTEND_ROOT, risk: 'médio', reason: 'Gera build de produção.' }; if (intent === 'git_status') return { action: 'git_status', command: 'git status --short', cwd: PROJECT_ROOT, risk: 'baixo', reason: 'Consulta Git sem alterar arquivos.' }; return null; }
function handleSovereignChat(message = '', approval = null) { const trimmed = String(message || '').trim(); if (!trimmed) return { ok: false, error: 'Mensagem vazia.' }; if (approval?.approved && approval?.command && approval?.cwd) { const result = runCommand(approval.command, approval.cwd); const decision = pushDecision({ intent: 'approved_execution', message: trimmed, result }); pushHistory({ type: 'approved_command', message: trimmed, result }); return { ok: result.ok, mode: 'executed_after_approval', decision, result }; } const intent = classifyIntent(trimmed); const proposal = proposalFor(intent); if (proposal) { const decision = pushDecision({ intent, message: trimmed, decision: 'approval_required', proposal }); pushHistory({ type: 'proposal', message: trimmed, proposal }); return { ok: true, mode: 'approval_required', message: 'Ação operacional detectada. Confirme para executar com segurança.', decision, proposal }; } let data; if (intent === 'status') data = getSovereignStatus(); else if (intent === 'audit') data = auditSystem(); else if (intent === 'tasks') data = { tasks: listTasks() }; else if (intent === 'decisions') data = { decisions: listDecisions() }; else if (intent === 'priority') data = buildPriorityAnswer(); else if (intent === 'memory') data = { memory: getStrategicMemory() }; else if (intent === 'create_task') data = { task: createTask({ text: trimmed.replace(/^(criar tarefa|delegar tarefa)[:\s-]*/i, '').trim() || trimmed, priority: /urgente|crítico|critico/i.test(trimmed) ? 'urgent' : 'normal', source: 'sovereign-chat' }) }; else data = { executiveAnswer: 'Entendi. Posso consultar status, auditar, priorizar, criar tarefas, consultar memória e propor comandos com aprovação.', examples: ['como estamos?', 'validar sistema agora', 'qual próximo passo?', 'criar tarefa: revisar Supabase', 'npm install backend', 'build frontend'] }; const decision = pushDecision({ intent, message: trimmed, decision: 'answered' }); pushHistory({ type: 'chat', message: trimmed, intent }); return { ok: true, mode: intent, decision, data }; }
module.exports = { getSovereignStatus, getStrategicMemory, auditSystem, handleSovereignChat, createTask, listTasks, listDecisions };
