const { findIntegration, getIntegrations } = require('./integration-registry.service');
const history = require('./automation-history.service');
async function requestJson(url, options={}){ const r=await fetch(url,options); const text=await r.text(); let data=null; try{data=text?JSON.parse(text):null;}catch{data={raw:text};} if(!r.ok){const e=new Error((data && data.error && data.error.message) || data?.message || 'HTTP ' + r.status); e.data=data; throw e;} return data; }
function requireConfigured(integration){ if(!integration) throw new Error('Integração não encontrada.'); if(!integration.configured) throw new Error('Credenciais ausentes para ' + integration.name + ': ' + integration.missingEnv.join(', ')); }
function dryRun(integration, action, payload){ return { ok:true, dryRun:true, integration:integration.id, action, message:integration.name + ' pronto para execução real quando execute=true e o .env estiver configurado.', payloadPreview:payload||{} }; }
async function runTelegram(action,payload,execute){ const i=findIntegration('telegram'); if(!execute) return dryRun(i,action,payload); requireConfigured(i); const token=process.env.TELEGRAM_BOT_TOKEN; if(action==='check_status') return requestJson('https://api.telegram.org/bot'+token+'/getMe'); if(action==='send_message') return requestJson('https://api.telegram.org/bot'+token+'/sendMessage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:payload.chatId||process.env.TELEGRAM_CHAT_ID,text:payload.text||'Mensagem da Megan OS 4.2.'})}); throw new Error('Ação Telegram não suportada.'); }
async function runGitHub(action,payload,execute){ const i=findIntegration('github'); if(!execute) return dryRun(i,action,payload); requireConfigured(i); const owner=process.env.GITHUB_OWNER, repo=process.env.GITHUB_REPO; const h={Authorization:'Bearer '+process.env.GITHUB_TOKEN,'User-Agent':'Megan-OS-4.2','Content-Type':'application/json'}; if(action==='check_status') return requestJson('https://api.github.com/repos/'+owner+'/'+repo,{headers:h}); if(action==='create_issue') return requestJson('https://api.github.com/repos/'+owner+'/'+repo+'/issues',{method:'POST',headers:h,body:JSON.stringify({title:payload.title||'Tarefa Megan OS 4.2',body:payload.body||'Issue criada pela automação 4.2.'})}); throw new Error('Ação GitHub não suportada.'); }
async function runGmail(action,payload,execute){ const i=findIntegration('gmail'); if(!execute) return dryRun(i,action,payload); requireConfigured(i); if(action==='check_status') return requestJson('https://gmail.googleapis.com/gmail/v1/users/me/profile',{headers:{Authorization:'Bearer '+process.env.GMAIL_ACCESS_TOKEN}}); if(action==='send_email'){ if(!payload.to) throw new Error('Campo obrigatório ausente: to'); const raw=Buffer.from(['From: '+process.env.GMAIL_FROM_EMAIL,'To: '+payload.to,'Subject: '+(payload.subject||'Mensagem Megan OS'),'Content-Type: text/plain; charset="UTF-8"','',payload.body||'Mensagem enviada pela Megan OS 4.2.'].join('\\n')).toString('base64url'); return requestJson('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:{Authorization:'Bearer '+process.env.GMAIL_ACCESS_TOKEN,'Content-Type':'application/json'},body:JSON.stringify({raw})}); } throw new Error('Ação Gmail não suportada.'); }
async function runWhatsApp(action,payload,execute){ const i=findIntegration('whatsapp'); if(!execute) return dryRun(i,action,payload); requireConfigured(i); const base='https://graph.facebook.com/v20.0/'+process.env.WHATSAPP_PHONE_NUMBER_ID; if(action==='check_status') return requestJson(base,{headers:{Authorization:'Bearer '+process.env.WHATSAPP_TOKEN}}); if(action==='send_message'){ if(!payload.to) throw new Error('Campo obrigatório ausente: to'); return requestJson(base+'/messages',{method:'POST',headers:{Authorization:'Bearer '+process.env.WHATSAPP_TOKEN,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:payload.to,type:'text',text:{body:payload.text||'Mensagem da Megan OS 4.2.'}})}); } throw new Error('Ação WhatsApp não suportada.'); }
async function runCalendar(action,payload,execute){ const i=findIntegration('google_calendar'); if(!execute) return dryRun(i,action,payload); requireConfigured(i); const id=encodeURIComponent(process.env.GOOGLE_CALENDAR_ID||'primary'); const h={Authorization:'Bearer '+process.env.GOOGLE_ACCESS_TOKEN,'Content-Type':'application/json'}; if(action==='check_status') return requestJson('https://www.googleapis.com/calendar/v3/calendars/'+id,{headers:h}); if(action==='create_event'){ const start=payload.start||new Date(Date.now()+3600000).toISOString(); const end=payload.end||new Date(Date.now()+7200000).toISOString(); return requestJson('https://www.googleapis.com/calendar/v3/calendars/'+id+'/events',{method:'POST',headers:h,body:JSON.stringify({summary:payload.title||'Evento Megan OS',description:payload.description||'',start:{dateTime:start},end:{dateTime:end}})}); } throw new Error('Ação Calendar não suportada.'); }
async function runSheets(action,payload,execute){ const i=findIntegration('google_sheets'); if(!execute) return dryRun(i,action,payload); requireConfigured(i); const h={Authorization:'Bearer '+process.env.GOOGLE_ACCESS_TOKEN,'Content-Type':'application/json'}; if(action==='check_status') return requestJson('https://sheets.googleapis.com/v4/spreadsheets/'+process.env.GOOGLE_SHEET_ID,{headers:h}); if(action==='append_row'){ const range=encodeURIComponent(payload.range||'Página1!A1'); return requestJson('https://sheets.googleapis.com/v4/spreadsheets/'+process.env.GOOGLE_SHEET_ID+'/values/'+range+':append?valueInputOption=USER_ENTERED',{method:'POST',headers:h,body:JSON.stringify({values:payload.values||[[new Date().toISOString(),'Megan OS 4.2','automação']]})}); } throw new Error('Ação Sheets não suportada.'); }
async function runStripe(action,payload,execute){ const i=findIntegration('stripe'); if(!execute) return dryRun(i,action,payload); requireConfigured(i); return requestJson('https://api.stripe.com/v1/customers?limit=5',{headers:{Authorization:'Bearer '+process.env.STRIPE_SECRET_KEY}}); }
async function runSupabase(action,payload,execute){ const i=findIntegration('supabase'); if(!execute) return dryRun(i,action,payload); requireConfigured(i); const table=payload.table||'megan_events'; const h={apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY,'Content-Type':'application/json'}; if(action==='check_status') return requestJson(process.env.SUPABASE_URL+'/rest/v1/'+table+'?select=*&limit=1',{headers:h}); if(action==='insert_row') return requestJson(process.env.SUPABASE_URL+'/rest/v1/'+table,{method:'POST',headers:{...h,Prefer:'return=representation'},body:JSON.stringify(payload.row||{source:'megan-os-4.2',created_at:new Date().toISOString()})}); throw new Error('Ação Supabase não suportada.'); }
async function runRender(action,payload,execute){ const i=findIntegration('render'); if(!execute) return dryRun(i,action,payload); requireConfigured(i); return requestJson('https://api.render.com/v1/services?limit=20',{headers:{Authorization:'Bearer '+process.env.RENDER_API_KEY}}); }
async function runVercel(action,payload,execute){ const i=findIntegration('vercel'); if(!execute) return dryRun(i,action,payload); requireConfigured(i); return requestJson('https://api.vercel.com/v9/projects',{headers:{Authorization:'Bearer '+process.env.VERCEL_TOKEN}}); }
async function runCrm(action,payload,execute){ const i=findIntegration('external_crm'); if(!execute) return dryRun(i,action,payload); requireConfigured(i); const url=String(process.env.CRM_API_URL).replace(/\/$/,''); if(action==='check_status') return requestJson(url+'/health',{headers:{Authorization:'Bearer '+process.env.CRM_API_KEY}}); if(action==='create_lead') return requestJson(url+'/leads',{method:'POST',headers:{Authorization:'Bearer '+process.env.CRM_API_KEY,'Content-Type':'application/json'},body:JSON.stringify(payload.lead||payload)}); throw new Error('Ação CRM não suportada.'); }
const runners={gmail:runGmail,whatsapp:runWhatsApp,google_calendar:runCalendar,google_sheets:runSheets,stripe:runStripe,supabase:runSupabase,render:runRender,vercel:runVercel,github:runGitHub,telegram:runTelegram,external_crm:runCrm};
async function executeAutomation({integrationId,action='check_status',payload={},execute=false}={}){ const integration=findIntegration(integrationId); if(!integration) throw new Error('Integração inválida.'); if(!integration.actions.includes(action)) throw new Error('Ação '+action+' não liberada para '+integration.name+'.'); const startedAt=Date.now(); try{ const result=await runners[integrationId](action,payload,Boolean(execute)); const entry=history.addHistory({integrationId,integrationName:integration.name,action,execute:Boolean(execute),ok:true,durationMs:Date.now()-startedAt,resultPreview:result?.message||result?.id||'ok'}); return {ok:true,version:'4.2.0',automation:entry,result}; }catch(error){ const entry=history.addHistory({integrationId,integrationName:integration.name,action,execute:Boolean(execute),ok:false,durationMs:Date.now()-startedAt,error:error.message}); return {ok:false,version:'4.2.0',automation:entry,error:error.message,details:error.data||null}; } }
function buildWorkflow(goal=''){ const text=String(goal).toLowerCase(); const all=getIntegrations(); const selected=all.filter(i=> text.includes(i.id) || text.includes(i.name.toLowerCase())); const targets=selected.length?selected:all.filter(i=>['gmail','google_calendar','google_sheets','telegram','github'].includes(i.id)); return {ok:true,version:'4.2.0',title:'Megan OS 4.2 — Automação Total Entre Apps',goal:goal||'Executar tarefa real entre aplicativos conectados.',selectedIntegrations:targets,steps:targets.map((i,n)=>({step:n+1,integrationId:i.id,integrationName:i.name,action:i.actions[0],status:i.configured?'ready':'needs_credentials',requirement:i.configured?'Pode executar com execute=true':'Configurar: '+i.missingEnv.join(', ')})),safety:{defaultMode:'dryRun',realExecution:'somente quando execute=true',destructiveActions:'bloqueadas nesta fase'}}; }
module.exports={executeAutomation,buildWorkflow};
